import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const badgesDir = path.join(root, 'assets', 'badges');
const outPath = path.join(root, '_data', 'dial_badges.yml');
const renderHeight = 40;

const entries = fs
  .readdirSync(badgesDir)
  .filter((file) => file.startsWith('download-on-the-app-store-') && file.endsWith('.svg'))
  .sort();

const sizes = {};

for (const file of entries) {
  const lang = file.slice('download-on-the-app-store-'.length, -'.svg'.length);
  const content = fs.readFileSync(path.join(badgesDir, file), 'utf8');
  const match = content.match(/viewBox="([^"]+)"/);
  if (!match) {
    throw new Error(`Missing viewBox in ${file}`);
  }

  const [, , viewWidth, viewHeight] = match[1].trim().split(/\s+/).map(Number);
  const width = Math.round((viewWidth / viewHeight) * renderHeight);
  sizes[lang] = { width, height: renderHeight };
}

const lines = [
  '# Generated by scripts/badge-sizes.mjs. Do not edit by hand.',
  '# Locale keys are quoted so YAML 1.1 does not treat "no" as boolean false.',
];
for (const lang of Object.keys(sizes).sort()) {
  const { width, height } = sizes[lang];
  lines.push(`"${lang}":`);
  lines.push(`  width: ${width}`);
  lines.push(`  height: ${height}`);
}

fs.writeFileSync(outPath, `${lines.join('\n')}\n`);
console.log(`Wrote ${Object.keys(sizes).length} badge sizes to ${path.relative(root, outPath)}`);
