#!/usr/bin/env python3
"""Pull Dial customer prices from App Store Connect into the site data files.

Uses `asc iap/subscriptions pricing summary --territory` (the live customer
price, not equalized automatic points). Mapping and notes live in
_data/dial_storefronts.yml and are not overwritten.

_data/dial_prices.yml holds one row per site language. _data/dial_currency_prices.yml
holds one row per App Store currency that no language storefront covers, so the
currency picker offers every currency App Store Connect lists.

    python3 scripts/sync-dial-prices.py
    python3 scripts/sync-dial-prices.py --dry-run
    python3 scripts/sync-dial-prices.py --check
    python3 scripts/sync-dial-prices.py --self-test
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import time
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path

SITE = Path(__file__).resolve().parents[1]
STOREFRONTS = SITE / "_data" / "dial_storefronts.yml"
PRICES = SITE / "_data" / "dial_prices.yml"
CURRENCY_PRICES = SITE / "_data" / "dial_currency_prices.yml"

APP_ID = "6789408903"
LIFETIME_IAP = "6789444088"
ANNUAL_SUB = "6789973352"
MONTHLY_SUB = "6789973283"

ALWAYS_CENTS = {"USD", "EUR", "BRL", "PLN", "SAR", "TRY", "MYR", "ILS", "RON"}
DOT_GROUP = {"RUB", "TRY", "IDR", "VND", "CZK", "HUF", "CLP", "COP"}
PREFIX = {
    "USD": "$",
    "MXN": "MX$",
    "JPY": "¥",
    "BRL": "R$",
    "RUB": "₽",
    "CNY": "¥",
    "TWD": "NT$",
    "KRW": "₩",
    "SAR": "SAR ",
    "TRY": "₺",
    "INR": "₹",
    "IDR": "Rp",
    "THB": "฿",
    "VND": "₫",
    "MYR": "RM",
    "ILS": "₪",
    "DKK": "DKK ",
    "SEK": "SEK ",
    "NOK": "NOK ",
    "HKD": "HK$",
    "GBP": "£",
    "AUD": "A$",
    "CAD": "CA$",
    "NZD": "NZ$",
    "SGD": "S$",
    "PHP": "₱",
    "NGN": "₦",
    "PEN": "S/ ",
}
SUFFIX = {
    "EUR": " €",
    "PLN": " zł",
    "CZK": " Kč",
    "HUF": " Ft",
    "RON": " lei",
}
COMMA_DECIMAL = {"EUR", "BRL", "PLN", "TRY", "MYR", "RON"}

HEADER = """\
# Generated by scripts/sync-dial-prices.py from live App Store Connect.
# Do not hand-edit amounts. Re-run the script after an ASC price change.
# Language-to-storefront mapping and price notes: _data/dial_storefronts.yml
"""

CURRENCY_HEADER = """\
# Generated by scripts/sync-dial-prices.py from live App Store Connect.
# Do not hand-edit amounts. Re-run the script after an ASC price change.
# One row per App Store currency that no language storefront in
# _data/dial_storefronts.yml covers. Territory is the first ASC territory
# that prices in that currency.
"""

DISPLAY_FIELDS = (
    "territory",
    "currency",
    "monthly",
    "annual",
    "lifetime",
    "monthly_display",
    "annual_display",
    "lifetime_display",
)


def load_storefronts() -> dict[str, dict[str, str]]:
    result = subprocess.run(
        ["ruby", "-ryaml", "-rjson", "-e", "puts YAML.load_file(ARGV[0]).to_json", str(STOREFRONTS)],
        check=True,
        capture_output=True,
        text=True,
    )
    data = json.loads(result.stdout)
    if not data:
        raise SystemExit(f"no storefronts in {STOREFRONTS}")
    return data


def schema_amount(raw: str) -> str:
    value = Decimal(raw)
    if value == value.to_integral():
        return str(int(value))
    return str(value.quantize(Decimal("0.01"), rounding=ROUND_HALF_UP))


def group_thousands(digits: str, separator: str) -> str:
    if len(digits) <= 3:
        return digits
    parts = []
    while digits:
        parts.append(digits[-3:])
        digits = digits[:-3]
    return separator.join(reversed(parts))


def format_display(raw: str, currency: str) -> str:
    value = Decimal(raw)
    cents = currency in ALWAYS_CENTS or value != value.to_integral()
    quantized = (
        value.quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
        if cents
        else value.to_integral_value(rounding=ROUND_HALF_UP)
    )
    formatted = f"{quantized:.2f}" if cents else f"{int(quantized)}"
    whole, _, fraction = formatted.partition(".")
    grouped = group_thousands(whole, "." if currency in DOT_GROUP else ",")
    number = f"{grouped}{',' if currency in COMMA_DECIMAL else '.'}{fraction}" if fraction else grouped
    prefix = PREFIX.get(currency)
    suffix = SUFFIX.get(currency, "")
    if prefix is None:
        prefix = "" if suffix else f"{currency} "
    return f"{prefix}{number}{suffix}"


def asc_json(args: list[str]) -> dict:
    for attempt in range(3):
        result = subprocess.run(
            ["asc", *args, "--output", "json"], capture_output=True, text=True,
        )
        if result.returncode == 0:
            return json.loads(result.stdout)
        if attempt == 2:
            raise RuntimeError(f"ASC read failed: {args}: {result.stderr.strip()}")
        time.sleep(10 * (attempt + 1))


def fetch_territory(territory: str) -> dict[str, str]:
    lifetime = asc_json(
        ["iap", "pricing", "summary", "--app", APP_ID, "--iap-id", LIFETIME_IAP, "--territory", territory]
    )["iaps"][0]["currentPrice"]
    subscriptions = {
        item["id"]: item["currentPrice"]
        for item in asc_json(
            ["subscriptions", "pricing", "summary", "--app", APP_ID, "--territory", territory]
        )["subscriptions"]
    }
    annual = subscriptions[ANNUAL_SUB]
    monthly = subscriptions[MONTHLY_SUB]
    currencies = {lifetime["currency"], annual["currency"], monthly["currency"]}
    if len(currencies) != 1:
        raise SystemExit(f"{territory}: mixed currencies {currencies}")
    return {
        "territory": territory,
        "currency": lifetime["currency"],
        "monthly": schema_amount(monthly["amount"]),
        "annual": schema_amount(annual["amount"]),
        "lifetime": schema_amount(lifetime["amount"]),
    }


def with_display(row: dict[str, str]) -> dict[str, str]:
    currency = row["currency"]
    return {
        **row,
        "monthly_display": format_display(row["monthly"], currency),
        "annual_display": format_display(row["annual"], currency),
        "lifetime_display": format_display(row["lifetime"], currency),
    }


def fetch_logged(territory: str) -> dict[str, str]:
    row = fetch_territory(territory)
    print(f"fetched {territory} {row['currency']}", file=sys.stderr)
    return row


def build_prices(storefronts: dict[str, dict[str, str]]) -> dict[str, dict[str, str]]:
    territories = sorted({row["territory"] for row in storefronts.values()})
    fetched = {territory: fetch_logged(territory) for territory in territories}
    return {lang: with_display(fetched[storefront["territory"]]) for lang, storefront in storefronts.items()}


def first_territory_by_currency() -> dict[str, str]:
    response = asc_json(["pricing", "territories", "list", "--paginate"])
    territories = response["data"] if isinstance(response, dict) else response
    first: dict[str, str] = {}
    for territory in sorted(territories, key=lambda item: item["id"]):
        first.setdefault(territory["attributes"]["currency"], territory["id"])
    return first


def build_currency_prices(prices: dict[str, dict[str, str]]) -> dict[str, dict[str, str]]:
    covered = {row["currency"] for row in prices.values()}
    uncovered = {
        currency: territory
        for currency, territory in sorted(first_territory_by_currency().items())
        if currency not in covered
    }
    currency_prices = {}
    for currency, territory in uncovered.items():
        row = fetch_logged(territory)
        if row["currency"] != currency:
            raise SystemExit(f"{territory}: ASC lists {currency} but prices in {row['currency']}")
        currency_prices[currency] = with_display(row)
    return currency_prices


def emit_yaml(header: str, rows: dict[str, dict[str, str]]) -> str:
    lines = [header.rstrip(), ""]
    for key, row in rows.items():
        lines.append('"no":' if key == "no" else f"{key}:")
        for field in DISPLAY_FIELDS:
            value = row[field]
            rendered = value if field in {"territory", "currency"} else json.dumps(value, ensure_ascii=False)
            lines.append(f"  {field}: {rendered}")
        lines.append("")
    return "\n".join(lines)


def load_yaml(path: Path) -> dict[str, dict[str, str]]:
    result = subprocess.run(
        ["ruby", "-ryaml", "-rjson", "-e", "puts YAML.load_file(ARGV[0]).to_json", str(path)],
        check=True,
        capture_output=True,
        text=True,
    )
    return json.loads(result.stdout) or {}


def self_test() -> int:
    tables = {PRICES: load_yaml(PRICES), CURRENCY_PRICES: load_yaml(CURRENCY_PRICES)}
    failures = 0
    for path, rows in tables.items():
        for key, row in rows.items():
            for sku in ("monthly", "annual", "lifetime"):
                got = format_display(row[sku], row["currency"])
                expected = row[f"{sku}_display"]
                if got != expected:
                    print(f"{path.name} {key} {sku}: {got!r} != {expected!r}", file=sys.stderr)
                    failures += 1
    language_currencies = {row["currency"] for row in tables[PRICES].values()}
    for currency in sorted(language_currencies & set(tables[CURRENCY_PRICES])):
        print(f"{CURRENCY_PRICES.name} {currency} duplicates a language storefront", file=sys.stderr)
        failures += 1
    if failures:
        print(f"{failures} price data problems", file=sys.stderr)
        return 1
    count = sum(len(rows) for rows in tables.values())
    print(f"ok: {count} price rows match the display formatter")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true", help="print YAML without writing")
    parser.add_argument("--check", action="store_true", help="exit 1 if the site file is stale")
    parser.add_argument("--self-test", action="store_true", help="check display formatting only")
    args = parser.parse_args()
    if args.self_test:
        return self_test()

    prices = build_prices(load_storefronts())
    currency_prices = build_currency_prices(prices)
    outputs = {
        PRICES: emit_yaml(HEADER, prices),
        CURRENCY_PRICES: emit_yaml(CURRENCY_HEADER, currency_prices),
    }
    if args.check:
        stale = [path for path, text in outputs.items() if (path.read_text() if path.exists() else "") != text]
        for path in stale:
            print(f"{path} is stale; run scripts/sync-dial-prices.py", file=sys.stderr)
        if stale:
            return 1
        print("ok: Dial price data matches live ASC")
        return 0
    if args.dry_run:
        for text in outputs.values():
            sys.stdout.write(text)
        return 0
    for path, text in outputs.items():
        path.write_text(text)
    print(
        f"wrote {PRICES} ({len(prices)} locales) and {CURRENCY_PRICES} ({len(currency_prices)} currencies)",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
