#!/usr/bin/env python3
"""Pull Dial customer prices from App Store Connect into _data/dial_prices.yml.

Uses `asc iap/subscriptions pricing summary --territory` (the live customer
price, not equalized automatic points). Mapping and notes live in
_data/dial_storefronts.yml and are not overwritten.

    python3 scripts/sync-dial-prices.py
    python3 scripts/sync-dial-prices.py --dry-run
    python3 scripts/sync-dial-prices.py --check
    python3 scripts/sync-dial-prices.py --self-test
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from concurrent.futures import ThreadPoolExecutor
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path

SITE = Path(__file__).resolve().parents[1]
STOREFRONTS = SITE / "_data" / "dial_storefronts.yml"
PRICES = SITE / "_data" / "dial_prices.yml"

APP_ID = "6789408903"
LIFETIME_IAP = "6789444088"
ANNUAL_SUB = "6789973352"
MONTHLY_SUB = "6789973283"

ALWAYS_CENTS = {"USD", "EUR", "BRL", "PLN", "SAR", "TRY", "MYR", "ILS", "RON"}
DOT_GROUP = {"RUB", "TRY", "IDR", "VND", "CZK", "HUF"}
PREFIX = {
    "USD": "$",
    "MXN": "MX$",
    "JPY": "¥",
    "BRL": "R$",
    "RUB": "₽",
    "CNY": "¥",
    "TWD": "NT$",
    "KRW": "₩",
    "SAR": "SAR ",
    "TRY": "₺",
    "INR": "₹",
    "IDR": "Rp",
    "THB": "฿",
    "VND": "₫",
    "MYR": "RM",
    "ILS": "₪",
    "DKK": "DKK ",
    "SEK": "SEK ",
    "NOK": "NOK ",
}
SUFFIX = {
    "EUR": " €",
    "PLN": " zł",
    "CZK": " Kč",
    "HUF": " Ft",
    "RON": " lei",
}
COMMA_DECIMAL = {"EUR", "BRL", "PLN", "TRY", "MYR", "RON"}

HEADER = """\
# Generated by scripts/sync-dial-prices.py from live App Store Connect.
# Do not hand-edit amounts. Re-run the script after an ASC price change.
# Language-to-storefront mapping and price notes: _data/dial_storefronts.yml
"""


def load_storefronts() -> dict[str, dict[str, str]]:
    result = subprocess.run(
        ["ruby", "-ryaml", "-rjson", "-e", "puts YAML.load_file(ARGV[0]).to_json", str(STOREFRONTS)],
        check=True,
        capture_output=True,
        text=True,
    )
    data = json.loads(result.stdout)
    if not data:
        raise SystemExit(f"no storefronts in {STOREFRONTS}")
    return data


def schema_amount(raw: str) -> str:
    value = Decimal(raw)
    if value == value.to_integral():
        return str(int(value))
    return str(value.quantize(Decimal("0.01"), rounding=ROUND_HALF_UP))


def group_thousands(digits: str, separator: str) -> str:
    if len(digits) <= 3:
        return digits
    parts = []
    while digits:
        parts.append(digits[-3:])
        digits = digits[:-3]
    return separator.join(reversed(parts))


def format_display(raw: str, currency: str) -> str:
    value = Decimal(raw)
    cents = currency in ALWAYS_CENTS or value != value.to_integral()
    quantized = (
        value.quantize(Decimal("0.01"), rounding=ROUND_HALF_UP)
        if cents
        else value.to_integral_value(rounding=ROUND_HALF_UP)
    )
    formatted = f"{quantized:.2f}" if cents else f"{int(quantized)}"
    whole, _, fraction = formatted.partition(".")
    grouped = group_thousands(whole, "." if currency in DOT_GROUP else ",")
    number = f"{grouped}{',' if currency in COMMA_DECIMAL else '.'}{fraction}" if fraction else grouped
    prefix = PREFIX.get(currency)
    suffix = SUFFIX.get(currency, "")
    if prefix is None:
        prefix = "" if suffix else f"{currency} "
    return f"{prefix}{number}{suffix}"


def asc_json(args: list[str]) -> dict:
    result = subprocess.run(
        ["asc", *args, "--output", "json"],
        check=True,
        capture_output=True,
        text=True,
    )
    return json.loads(result.stdout)


def fetch_territory(territory: str) -> dict[str, str]:
    lifetime = asc_json(
        ["iap", "pricing", "summary", "--app", APP_ID, "--iap-id", LIFETIME_IAP, "--territory", territory]
    )["iaps"][0]["currentPrice"]
    subscriptions = {
        item["id"]: item["currentPrice"]
        for item in asc_json(
            ["subscriptions", "pricing", "summary", "--app", APP_ID, "--territory", territory]
        )["subscriptions"]
    }
    annual = subscriptions[ANNUAL_SUB]
    monthly = subscriptions[MONTHLY_SUB]
    currencies = {lifetime["currency"], annual["currency"], monthly["currency"]}
    if len(currencies) != 1:
        raise SystemExit(f"{territory}: mixed currencies {currencies}")
    return {
        "territory": territory,
        "currency": lifetime["currency"],
        "monthly": schema_amount(monthly["amount"]),
        "annual": schema_amount(annual["amount"]),
        "lifetime": schema_amount(lifetime["amount"]),
    }


def build_prices(storefronts: dict[str, dict[str, str]]) -> dict[str, dict[str, str]]:
    territories = sorted({row["territory"] for row in storefronts.values()})
    fetched: dict[str, dict[str, str]] = {}
    with ThreadPoolExecutor(max_workers=4) as pool:
        for territory, row in zip(territories, pool.map(fetch_territory, territories)):
            print(f"fetched {territory} {row['currency']}", file=sys.stderr)
            fetched[territory] = row
    prices = {}
    for lang, storefront in storefronts.items():
        row = dict(fetched[storefront["territory"]])
        currency = row["currency"]
        row["monthly_display"] = format_display(row["monthly"], currency)
        row["annual_display"] = format_display(row["annual"], currency)
        row["lifetime_display"] = format_display(row["lifetime"], currency)
        prices[lang] = row
    return prices


def emit_yaml(prices: dict[str, dict[str, str]]) -> str:
    lines = [HEADER.rstrip(), ""]
    fields = (
        "territory",
        "currency",
        "monthly",
        "annual",
        "lifetime",
        "monthly_display",
        "annual_display",
        "lifetime_display",
    )
    for lang, row in prices.items():
        lines.append('"no":' if lang == "no" else f"{lang}:")
        for field in fields:
            value = row[field]
            rendered = value if field in {"territory", "currency"} else json.dumps(value, ensure_ascii=False)
            lines.append(f"  {field}: {rendered}")
        lines.append("")
    return "\n".join(lines)


def load_prices() -> dict[str, dict[str, str]]:
    result = subprocess.run(
        ["ruby", "-ryaml", "-rjson", "-e", "puts YAML.load_file(ARGV[0]).to_json", str(PRICES)],
        check=True,
        capture_output=True,
        text=True,
    )
    return json.loads(result.stdout)


def self_test() -> int:
    prices = load_prices()
    failures = 0
    for lang, row in prices.items():
        for sku in ("monthly", "annual", "lifetime"):
            got = format_display(row[sku], row["currency"])
            expected = row[f"{sku}_display"]
            if got != expected:
                print(f"{lang} {sku}: {got!r} != {expected!r}", file=sys.stderr)
                failures += 1
    if failures:
        print(f"{failures} display mismatches", file=sys.stderr)
        return 1
    print(f"ok: {len(prices)} locales match the display formatter")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true", help="print YAML without writing")
    parser.add_argument("--check", action="store_true", help="exit 1 if the site file is stale")
    parser.add_argument("--self-test", action="store_true", help="check display formatting only")
    args = parser.parse_args()
    if args.self_test:
        return self_test()

    storefronts = load_storefronts()
    prices = build_prices(storefronts)
    text = emit_yaml(prices)
    if args.check:
        current = PRICES.read_text() if PRICES.exists() else ""
        if current != text:
            print(f"{PRICES} is stale; run scripts/sync-dial-prices.py", file=sys.stderr)
            return 1
        print(f"ok: {PRICES} matches live ASC")
        return 0
    if args.dry_run:
        sys.stdout.write(text)
        return 0
    PRICES.write_text(text)
    print(f"wrote {PRICES} ({len(prices)} locales)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
